import { jsPDF } from "jspdf";
import { QuizFormData, EmailFormData } from "@shared/schema";

interface GeneratePDFParams {
  quizData: QuizFormData;
  userData: EmailFormData;
  advice: string;
  affiliateLink: string;
}

export const generatePDF = ({
  quizData,
  userData,
  advice,
  affiliateLink
}: GeneratePDFParams): jsPDF => {
  // Create a new PDF document
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  // Set up document properties
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  
  // Add title with pink color
  doc.setTextColor(242, 59, 108); // #F23B6C
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Your Custom Obsession Trigger Plan", margin, margin);
  
  // Add subtitle
  doc.setTextColor(107, 114, 128); // gray-500
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Prepared specially for ${userData.firstName}`, margin, margin + 8);
  
  // Add divider
  doc.setDrawColor(229, 231, 235); // gray-200
  doc.line(margin, margin + 12, pageWidth - margin, margin + 12);
  
  // Add content
  doc.setTextColor(31, 41, 55); // gray-800
  doc.setFontSize(11);
  
  // Split advice into paragraphs and add with proper spacing
  const paragraphs = advice.split('\n\n');
  let yPosition = margin + 20;
  
  for (const paragraph of paragraphs) {
    const lines = doc.splitTextToSize(paragraph, contentWidth);
    doc.text(lines, margin, yPosition);
    yPosition += lines.length * 6 + 4; // Add spacing between paragraphs
  }
  
  // Add call to action box
  const ctaY = yPosition + 5;
  doc.setFillColor(249, 250, 251); // gray-50
  doc.setDrawColor(229, 231, 235); // gray-200
  doc.roundedRect(margin, ctaY, contentWidth, 20, 2, 2, 'FD');
  
  // Add CTA text
  doc.setTextColor(31, 41, 55); // gray-800
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("To learn the full system that activates his Hero Instinct, download His Secret Obsession.", margin + 5, ctaY + 8);
  
  doc.setTextColor(37, 99, 235); // blue-600
  doc.text(`Click here 👉 ${affiliateLink}`, margin + 5, ctaY + 15);
  
  // Add footer
  doc.setTextColor(107, 114, 128); // gray-500
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const currentDate = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
  const footerText = `Your custom plan generated by Obsession Trigger AI on ${currentDate}`;
  doc.text(footerText, pageWidth / 2, 280, { align: "center" });
  
  return doc;
};

export const downloadPDF = (doc: jsPDF, userName: string): void => {
  doc.save(`Obsession_Trigger_Plan_${userName}.pdf`);
};

export const getPDFDataUrl = (doc: jsPDF): string => {
  return doc.output('datauristring');
};
