import React from 'react';
import { Heart, Sparkles, Download } from 'lucide-react';

interface PDFPreviewProps {
  firstName: string;
  advice: string;
}

const PDFPreview: React.FC<PDFPreviewProps> = ({ firstName, advice }) => {
  const currentDate = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
  
  // Split advice into paragraphs
  const paragraphs = advice.split('\n\n');
  
  // Affiliate link for CTAs
  const affiliateLink = "https://hop.clickbank.net/?affiliate=otrigger&vendor=hissecret&lp=0&tid=quiz";

  return (
    <div className="border border-gray-200 rounded-lg p-4 mb-6 bg-white relative">
      <div className="flex justify-between items-center mb-4 border-b border-gray-100 pb-3">
        <div>
          <h3 className="font-script text-xl text-[#f24b7c]">Your Obsession Trigger Plan</h3>
          <p className="text-xs text-gray-600">For <span className="font-medium text-[#f24b7c]">{firstName}</span></p>
        </div>
        <div>
          <div className="w-10 h-10 bg-[#fde8ef] rounded-full flex items-center justify-center">
            <Heart className="text-[#f24b7c] h-5 w-5" fill="#fbb5c8" />
          </div>
        </div>
      </div>
      
      {/* AI-Generated Content Preview - Show just a sample with blur effect */}
      <div className="prose max-w-none mb-4 relative overflow-hidden" style={{ maxHeight: '200px' }}>
        {paragraphs.slice(0, 2).map((paragraph, index) => (
          <p key={index} className="mb-3 text-gray-700 text-sm">{paragraph}</p>
        ))}
        
        {/* Blur effect for content that continues in the PDF */}
        {paragraphs.length > 2 && (
          <>
            <div className="absolute bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-white to-transparent"></div>
            <div className="text-center text-xs text-[#f24b7c] absolute bottom-0 left-0 right-0">
              Full advice available in your PDF
            </div>
          </>
        )}
      </div>
      
      {/* Call to Action - Visual version matching the screenshot */}
      <div className="affiliate-callout p-4 my-6 border rounded-lg border-primary-200 bg-primary-50">
        <h4 className="font-medium text-primary-800 mb-2 text-sm">Expert Recommendation</h4>
        <p className="text-sm">
          His Secret Obsession specializes in activating a man's 'Hero Instinct' - the psychological trigger 
          that makes a man feel a deep biological drive to protect, provide for, and commit to the woman he 
          loves. Learn more about this powerful relationship technique: {' '}
          <a 
            href={affiliateLink}
            target="_blank"
            rel="noopener noreferrer" 
            className="text-primary-600 hover:underline font-medium"
          >
            His Secret Obsession
          </a>
        </p>
      </div>
      
      <div className="text-xs text-gray-500 text-center">
        Generated by Obsession Trigger on {currentDate}
      </div>
    </div>
  );
};

export default PDFPreview;
