import React from 'react';
import { Heart } from 'lucide-react';

interface PDFPreviewProps {
  firstName: string;
  advice: string;
}

const PDFPreview: React.FC<PDFPreviewProps> = ({ firstName, advice }) => {
  const currentDate = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
  
  // Split advice into paragraphs
  const paragraphs = advice.split('\n\n');

  return (
    <div className="border border-neutral-200 rounded-lg p-4 md:p-6 mb-6 bg-white">
      <div className="flex justify-between items-center mb-6 border-b border-neutral-100 pb-4">
        <div>
          <h3 className="font-script text-2xl text-primary-500">Your Custom Obsession Trigger Plan</h3>
          <p className="text-xs text-neutral-500">Prepared specially for {firstName}</p>
        </div>
        <div>
          <div className="w-10 h-10 bg-primary-100 rounded-full flex items-center justify-center">
            <Heart className="text-primary-500 h-5 w-5 fill-current" />
          </div>
        </div>
      </div>
      
      {/* AI-Generated Content Preview */}
      <div className="prose max-w-none mb-6">
        {paragraphs.map((paragraph, index) => (
          <p key={index} className="mb-4">{paragraph}</p>
        ))}
      </div>
      
      {/* Call to Action */}
      <div className="bg-neutral-50 p-4 rounded-lg border border-neutral-100 mb-4">
        <p className="text-sm text-neutral-700 font-medium">To learn the full system that activates his Hero Instinct, download <span className="font-bold text-primary-600">His Secret Obsession</span>.</p>
        <p className="text-sm text-primary-600">Click here 👉 [Affiliate Link]</p>
      </div>
      
      <div className="text-xs text-neutral-500 text-center">
        Your custom plan generated by Obsession Trigger AI on {currentDate}
      </div>
    </div>
  );
};

export default PDFPreview;
