import React from 'react';
import { Heart, Sparkles, Download } from 'lucide-react';

interface PDFPreviewProps {
  firstName: string;
  advice: string;
}

const PDFPreview: React.FC<PDFPreviewProps> = ({ firstName, advice }) => {
  const currentDate = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
  
  // Split advice into paragraphs
  const paragraphs = advice.split('\n\n');
  
  // Affiliate link for CTAs
  const affiliateLink = "https://hop.clickbank.net/?affiliate=otrigger&vendor=hissecret&lp=0&tid=quiz";

  return (
    <div className="border border-gray-200 rounded-lg p-4 mb-6 bg-white relative">
      <div className="flex justify-between items-center mb-4 border-b border-gray-100 pb-3">
        <div>
          <h3 className="font-script text-xl text-[#f24b7c]">Your Obsession Trigger Plan</h3>
          <p className="text-xs text-gray-600">For <span className="font-medium text-[#f24b7c]">{firstName}</span></p>
        </div>
        <div>
          <div className="w-10 h-10 bg-[#fde8ef] rounded-full flex items-center justify-center">
            <Heart className="text-[#f24b7c] h-5 w-5" fill="#fbb5c8" />
          </div>
        </div>
      </div>
      
      {/* AI-Generated Content Preview - Show just a sample with blur effect */}
      <div className="prose max-w-none mb-4 relative overflow-hidden" style={{ maxHeight: '200px' }}>
        {paragraphs.slice(0, 2).map((paragraph, index) => (
          <p key={index} className="mb-3 text-gray-700 text-sm">{paragraph}</p>
        ))}
        
        {/* Blur effect for content that continues in the PDF */}
        {paragraphs.length > 2 && (
          <>
            <div className="absolute bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-white to-transparent"></div>
            <div className="text-center text-xs text-[#f24b7c] absolute bottom-0 left-0 right-0">
              Full advice available in your PDF
            </div>
          </>
        )}
      </div>
      
      {/* Call to Action - Purely visual version for PDF preview */}
      <div className="bg-[#fde8ef] border border-primary-100 rounded-lg p-4 mb-4 text-center relative overflow-hidden">
        <div className="border-b border-primary-200 mb-3 pb-2">
          <h4 className="font-medium text-[#f24b7c] mb-1 text-sm">Complete Your Journey</h4>
        </div>
        
        <p className="text-xs text-gray-700 mb-3">
          To learn the full system that activates his Hero Instinct
        </p>
        
        <a 
          href={affiliateLink}
          target="_blank"
          rel="noopener noreferrer" 
          className="inline-block text-[#f24b7c] font-bold text-base hover:underline"
        >
          His Secret Obsession
        </a>
        
        <p className="text-[10px] text-gray-500 italic mt-1">(Click to download)</p>
      </div>
      
      <div className="text-xs text-gray-500 text-center">
        Generated by Obsession Trigger on {currentDate}
      </div>
    </div>
  );
};

export default PDFPreview;
